---
- name: Ensure Performance Prototype Platform (P-cubed) OpenStack nova flavors exist
  hosts: localhost
  roles:
    - role: stackhpc.os-flavors
      os_flavors_venv: "{{ p3_venv }}"
      os_flavors_auth_type: "{{ openstack_auth_type }}"
      os_flavors_auth: "{{ openstack_auth }}"
      os_flavors: "{{ p3_flavors }}"
